### ISSUE TITLE
Intro to numpy notebook

### ISSUE THREAD

**Issue by lekeOnilude** [DeltaAnalytics/machine_learning_for_good#51]
I think there should be a notebook that introduces the student to NumPy. NumPy is a very import tool in ML and in taking about NumPy with the student, the concept of vectors and matrics can be visualised which would be of great help to the student when they move into linear regression and other machine learning model

**Comment by CloudChaoszero** [comment]
@lekeOnilude Hope you are doing well! I am one of the Teaching Fellows that came aboard the recent past year, and happy to comment. 

Thanks for reaching out in regards to including NumPy concepts to be expanded for students.
That seems like a great idea to mention , if students had additional questions & curiosity about vectors and more, when it comes to more advanced topics like Linear Regression.

Would you think it would be sufficient to have resources or links to be added about Numpy, or actually adding a Jupyter Notebook in a different folder like `additional_content/Numpy` etc?
> Maybe adding links in a "READ ME" too?

Let me know your thoughts.

**Comment by brianspiering** [comment]
Those are good ideas. 

I'm the code lead for the project so I'll chime in with my perspective.

It is very class specific. Different learners have different histories and goals.

I'm hesitant to create a folder called `additional_content` which might become dumping ground / graveyard. 

NumPy belongs in Module 1 https://github.com/DeltaAnalytics/machine_learning_for_good/tree/master/module_1_introduction.

Module 1 needs a cleanup. Before we add more, let's improve what is already there:

- Two readmes. Needs a single readme.
- .pdfs and .pptx. Those should be converted to code, either Markdown or Jupyter Notebook.
- Re-order to following typically learning path

Then add a notebook covering numpy. Maybe before pandas because pandas typing depends on numpy typing.

**Comment by brianspiering** [comment]
I have clean-up the repo. 

If anyone wants to make a tutorial about numpy, aubmit a PR.

**Comment by lekeOnilude** [comment]
@CloudChaoszero I am doing ok thanks for asking.

If there is an online platform that curates all you need to know about Numpy into one page, then it will be ok but I will lend toward more of @brianspiering perspective.

Adding a notebook covering Numpy will be helpful to the students, we can then add links for further study below the notebook.

**Comment by lekeOnilude** [comment]
> I have clean-up the repo.
> 
> If anyone wants to make a tutorial about numpy, submit a PR.

working on this

**Comment by brianspiering** [comment]
Here it is https://github.com/DeltaAnalytics/machine_learning_for_good/pull/53
